"""update user

Revision ID: d451affc417a
Revises: cf8920d85251
Create Date: 2023-04-17 17:05:16.841737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd451affc417a'
down_revision = 'cf8920d85251'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'flask_user', ['username'])
    op.create_unique_constraint(None, 'flask_user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flask_user', type_='unique')
    op.drop_constraint(None, 'flask_user', type_='unique')
    # ### end Alembic commands ###
